/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface Product {
  'id' : bigint,
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
}
export interface SafetyArticle {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'publishedDate' : bigint,
  'summary' : string,
  'category' : string,
}
export interface Testimonial {
  'id' : bigint,
  'customerName' : string,
  'review' : string,
  'company' : string,
  'avatarUrl' : string,
  'rating' : bigint,
}
export interface _SERVICE {
  'addToCart' : ActorMethod<[string, bigint, bigint], boolean>,
  'clearCart' : ActorMethod<[string], boolean>,
  'getAllArticles' : ActorMethod<[], Array<SafetyArticle>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getCart' : ActorMethod<[string], Array<CartItem>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'removeFromCart' : ActorMethod<[string, bigint], boolean>,
  'seedData' : ActorMethod<[], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];